<?php

return [
    'WALLET_URL' => isset($_SERVER['WALLET_URL']) ? $_SERVER['WALLET_URL'] : '',
    'HOSTNAME' => isset($_SERVER['HTTP_HOST']) ? (isset($_SERVER['REQUEST_SCHEME']) ? $_SERVER['REQUEST_SCHEME'] : 'http')."://".$_SERVER['HTTP_HOST'] : '',
    'BALANCE_SETTING' => isset($_SERVER['BALANCE_SETTING']) ? $_SERVER['BALANCE_SETTING'] : '',
    'PREFIX' => 'api',
    'CARDHOLDER_EMAIL_DELIVERY' => isset($_SERVER['CARDHOLDER_EMAIL_DELIVERY']) ? $_SERVER['CARDHOLDER_EMAIL_DELIVERY'] : '',
    'FX_RATE' => isset($_SERVER['DEFAULT_FX_RATE']) ? $_SERVER['DEFAULT_FX_RATE'] : '1',
    'PREFUNDING_CURRENCY' => isset($_SERVER['DEFAULT_PREFUNDING_CURRENCY']) ? $_SERVER['DEFAULT_PREFUNDING_CURRENCY'] : 'SGD',
    'APP_CURRENCY' => isset($_SERVER['DEFAULT_APP_CURRENCY']) ? $_SERVER['DEFAULT_APP_CURRENCY'] : 'SGD',
    'LITERAL_BRAND_NAME' => isset($_SERVER['LITERAL_BRAND_NAME']) ? $_SERVER['LITERAL_BRAND_NAME'] : '',
    'DEFAULT_BRAND_NAME' => isset($_SERVER['DEFAULT_BRAND_NAME']) ? $_SERVER['DEFAULT_BRAND_NAME'] : '',
    'DEFAULT_PRODUCT_NAME' => isset($_SERVER['DEFAULT_PRODUCT_NAME']) ? $_SERVER['DEFAULT_PRODUCT_NAME'] : '',
    'GENERIC_PRODUCT_NAME' => isset($_SERVER['GENERIC_PRODUCT_NAME']) ? $_SERVER['GENERIC_PRODUCT_NAME'] : '',
    'CARD_BREAKAGE_SUPPORT' => isset($_SERVER['CARD_BREAKAGE_SUPPORT']) ? $_SERVER['CARD_BREAKAGE_SUPPORT'] : '',
    'S3_EXPIRY_TIME' => isset($_SERVER['S3_EXPIRY_TIME']) ? $_SERVER['S3_EXPIRY_TIME'] : '',
    'CLOUDWATCH_NAMESPACE' => isset($_SERVER['CLOUDWATCH_NAMESPACE']) ? $_SERVER['CLOUDWATCH_NAMESPACE'] : '',
    'PRODUCT_CODE' => isset($_SERVER['PRODUCT_CODE']) ? $_SERVER['PRODUCT_CODE'] : '',
    'APP_ENV' => isset($_SERVER['APP_ENV']) ? $_SERVER['APP_ENV'] : 'testing', // testing, local, production
    'MP_ENABLED' => isset($_SERVER['MASTERPASS_ENABLED']) ? $_SERVER['MASTERPASS_ENABLED'] : 0,
    'WEEK_START_DAY' => isset($_SERVER['DEFAULT_WEEK_START_DAY']) ? $_SERVER['DEFAULT_WEEK_START_DAY'] : 'Sunday',
    'WEEK_END_DAY' => isset($_SERVER['DEFAULT_WEEK_END_DAY']) ? $_SERVER['DEFAULT_WEEK_END_DAY'] : 'Saturday',
    'EKYC_ENABLED' => isset($_SERVER['EKYC_ENABLED']) ? $_SERVER['EKYC_ENABLED'] : '',

];